import { ArrowRight, BookOpen, Feather, ShieldCheck } from 'lucide-react';
export const metadata = { title: 'Ayuda · NOVA' };
const questions = [
    ['¿Cómo se guarda mi manuscrito?', 'Pulsa Guardar en el editor. Cada guardado del capítulo crea una versión. NOVA advierte al salir con cambios pendientes; no cierres la página si aún no has guardado.'],
    ['¿Cómo recupero una versión anterior?', 'Abre el historial del capítulo. Recuperar coloca esa versión en el editor. Revísala y pulsa Guardar para conservarla como la versión actual.'],
    ['¿Qué hago si aparece un conflicto de guardado?', 'Otro dispositivo o ventana modificó el mismo contenido. Copia tu texto pendiente antes de recargar, consulta la versión más reciente y reúne los cambios que quieras conservar.'],
    ['¿Qué archivos puedo añadir?', 'Las fuentes aceptan TXT y Markdown en UTF-8 o texto pegado. Las muestras de voz admiten TXT, Markdown o transcripciones pegadas. Para PDF o Word, copia el fragmento de texto; la extracción automática no está disponible.'],
    ['¿Mi voz y mi perfil son lo mismo?', 'El perfil contiene tu nombre visible y las preferencias del editor. Mi voz conserva muestras y criterios de escritura. Mi memoria guarda preferencias generales o de un proyecto.'],
    ['¿La inteligencia artificial está activa?', 'La integración del modelo sigue pendiente. Los ejercicios del perfil proceden de plantillas; las búsquedas encuentran coincidencias de texto. No se generan escritos ni se verifican hechos automáticamente.'],
    ['¿Cómo exporto mi trabajo?', 'Abre un proyecto y pulsa Exportar manuscrito para descargar Markdown. En la configuración del proyecto puedes descargar JSON con capítulos, fuentes y memoria. El JSON no incluye el historial ni tiene importación automática.'],
    ['¿Qué pasa si pierdo la conexión?', 'Mantén abierta la página para conservar el texto que estás editando. Cuando vuelva la conexión, guarda nuevamente. La advertencia de desconexión no sustituye la confirmación de un guardado correcto.'],
    ['¿Cómo cierro sesión?', 'Utiliza Cerrar sesión en el menú de usuario, la barra lateral o tu perfil. Guarda antes los cambios pendientes. Para volver a acceder a tu espacio privado necesitarás iniciar sesión.'],
];
export default function Help() { return <div className="help-page"><div className="page-head"><div><h1>Centro de ayuda</h1><p>Orientación para escribir, organizar y conservar tu trabajo.</p></div></div><div className="help-resources">{[['/proyectos', 'Tus proyectos', 'Manuscritos, capítulos y exportación.', BookOpen], ['/mi-voz', 'Tu voz de autor', 'Configura tus muestras y preferencias.', Feather], ['/confianza', 'Fuentes y datos', 'Conoce el alcance de cada herramienta.', ShieldCheck]].map(([href, title, description, Icon]: any) => <a href={href} key={href}><Icon size={23} strokeWidth={1.5}/><h2>{title}</h2><p>{description}</p><ArrowRight size={18}/></a>)}</div><section className="help-questions"><h2>Preguntas frecuentes</h2>{questions.map(([q, a]) => <article key={q}><h3>{q}</h3><p>{a}</p></article>)}</section><div className="help-bottom"><h2>Conoce el proceso completo</h2><p>Una guía desde la creación del proyecto hasta la exportación.</p><a className="btn secondary" href="/como-funciona">Cómo funciona NOVA<ArrowRight size={16}/></a></div></div>; }
