'use client';
import { useState } from 'react';
import { Plus, Search, ArrowUpRight, BookOpen } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { toast } from 'sonner';
import { api, useData, Loading, Failure, Empty, PageHead, Modal, Choice, SaveButton, kinds, num, date } from './ui';
export default function Projects() { const { data, error, loading, reload } = useData('projects'); const [search, setSearch] = useState(''), [filter, setFilter] = useState('active'), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [kind, setKind] = useState('novela'); if (loading)
    return <Loading />; if (error)
    return <Failure error={error} retry={reload}/>; const rows = data.filter((p: any) => (filter === 'all' || (filter === 'archived' ? p.archived : !p.archived)) && p.title.toLowerCase().includes(search.toLowerCase())); return <><PageHead eyebrow="BIBLIOTECA PERSONAL" title="Cada gran obra empieza aquí." description="Tus manuscritos, tus fuentes y tus ideas. Un proyecto a la vez." action={<button className="btn" onClick={() => setOpen(true)}><Plus size={18}/>Nuevo proyecto</button>}/><div className="summary-strip"><span><b>{num(data.filter((p: any) => !p.archived).length)}</b> proyectos activos</span><span><b>{num(data.reduce((n: number, p: any) => n + p.words, 0))}</b> palabras escritas</span><span><b>{num(data.reduce((n: number, p: any) => n + p.sources, 0))}</b> fuentes guardadas</span></div><div className="filter-bar"><label className="search-box"><Search size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar un proyecto…" aria-label="Buscar proyectos"/></label><Choice label="Filtrar proyectos" value={filter} onChange={setFilter} items={{ active: 'Activos', archived: 'Archivados', all: 'Todos' }}/></div>{rows.length ? <div className="project-grid">{rows.map((p: any) => <a className={'project-card ' + p.kind} key={p.id} href={'/proyectos/' + p.id}><div className="book-cover"><span>{kinds[p.kind]}</span><h2>{p.title}</h2><div className="cover-rule"/><small>NOVA / MANUSCRITO</small></div><div className="project-card-body"><div><span>{num(p.chapters)} capítulos</span><ArrowUpRight size={18}/></div><Progress value={Math.min(100, p.words / p.goal * 100)} aria-label="Avance hacia la meta"/><p>{num(p.words)} / {num(p.goal)} palabras</p><small>Actualizado el {date(p.updated)}{p.archived ? ' · Archivado' : ''}</small></div></a>)}</div> : <Empty title={search ? 'No encontramos ese proyecto.' : filter === 'archived' ? 'No tienes proyectos archivados.' : 'Tu primera página te espera.'}><p>{search ? 'Prueba otro título.' : 'Crea una novela, un ensayo o un libro académico y comienza a darle forma.'}</p>{!search && filter !== 'archived' ? <button className="btn" onClick={() => setOpen(true)}><Plus size={17}/>Crear mi primer proyecto</button> : null}</Empty>}<Modal open={open} onOpenChange={setOpen} title="Una nueva obra" description="Elige un punto de partida. Podrás cambiar estos detalles después."><form className="form-stack" onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); try {
    const p = await api('projects', 'POST', { title: f.get('title'), kind, description: f.get('description'), goal: Number(f.get('goal')) });
    window.location.assign('/proyectos/' + p.id);
}
catch (e) {
    toast.error((e as Error).message);
    setBusy(false);
} }}><label>Título del proyecto<input name="title" required maxLength={160} placeholder="El título de tu próxima obra"/></label><label>Tipo de obra<Choice label="Tipo de obra" value={kind} onChange={setKind} items={kinds}/></label><label>¿De qué trata?<textarea name="description" maxLength={5000} rows={3} placeholder="Una premisa, una pregunta o un objetivo…"/></label><label>Meta de palabras<input name="goal" type="number" min={1} max={2000000} defaultValue={50000} required/></label><SaveButton busy={busy} label="Crear proyecto"/></form></Modal><div className="quiet-note"><BookOpen size={18}/><p>Todo empieza en blanco. Las cifras reflejan tus proyectos reales, sin datos de ejemplo.</p></div></>; }
