'use client';
import { ArrowRight, Check, LogOut } from 'lucide-react';
import { useData, Loading, Failure, PageHead } from './ui';
export default function Settings() {
    const { data, loading, error, reload } = useData('status');
    if (loading)
        return <Loading />;
    if (error)
        return <Failure error={error} retry={reload}/>;
    return <div className="account-page"><PageHead eyebrow="CUENTA" title="Configuración" description="Consulta el estado de tu espacio y administra el acceso a tus datos."/>
    <section className="settings-section"><div><h2>Cuenta y sesión</h2><p>Tu identidad de acceso se administra con ChatGPT.</p></div><div className="settings-details"><dl><div><dt>Correo de la sesión</dt><dd>{data.user.email || 'No disponible'}</dd></div><div><dt>Acceso</dt><dd>Cuenta de ChatGPT</dd></div></dl><div className="settings-links"><a href="/perfil">Editar perfil<ArrowRight size={16}/></a><a href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={16}/>Cerrar sesión</a></div></div></section>
    <section className="settings-section"><div><h2>Escritura y personalización</h2><p>Configura la presentación del editor y las preferencias que quieres conservar.</p></div><div className="settings-details"><a className="settings-route" href="/perfil"><span><strong>Preferencias del editor</strong><small>Tipografía, tamaño y meta de proyectos nuevos.</small></span><ArrowRight size={18}/></a><a className="settings-route" href="/mi-voz"><span><strong>Perfil de voz</strong><small>Muestras, criterios y ejercicios de escritura.</small></span><ArrowRight size={18}/></a><a className="settings-route" href="/mi-memoria"><span><strong>Memoria personal</strong><small>Preferencias generales y por proyecto.</small></span><ArrowRight size={18}/></a></div></section>
    <section className="settings-section"><div><h2>Funciones disponibles</h2><p>Estado de las herramientas de tu espacio.</p></div><div className="settings-details"><dl>{['Edición y guardado de manuscritos', 'Historial de capítulos', 'Fuentes y búsqueda de texto', 'Perfil de voz y memoria', 'Exportación de proyectos'].map(s => <div key={s}><dt>{s}</dt><dd className="availability"><Check size={16}/>Disponible</dd></div>)}<div><dt>Asistencia con IA</dt><dd>{data.ai.available ? 'Proveedor conectado' : 'Pendiente de conexión'}</dd></div></dl><p>La generación, la reescritura y la verificación automática requieren conectar el modelo. Tus datos actuales permanecerán disponibles.</p></div></section>
    <section className="settings-section"><div><h2>Datos y exportación</h2><p>Conserva una copia de tu trabajo y gestiona tus documentos.</p></div><div className="settings-details"><p>Cada proyecto permite exportar el manuscrito en Markdown o sus capítulos, fuentes y memoria en JSON. El historial se consulta dentro del editor y no se incluye en el JSON.</p><p>Puedes eliminar muestras y recuerdos desde sus páginas. La eliminación de un proyecto es definitiva y se confirma en su configuración.</p><div className="settings-links"><a href="/proyectos">Ir a proyectos<ArrowRight size={16}/></a><a href="/confianza">Consultar el tratamiento de los datos<ArrowRight size={16}/></a></div></div></section>
  </div>;
}
